return {
    'nvim-treesitter/nvim-treesitter',
    lazy = false,
    build = ':TSUpdate',
    opts = {
        auto_install = true,
        indent = { enable = true },
        highlight = { enable = true },
        folds = { enable = true },
        ensure_installed = {
            "bash",
            "html",
            "css",
            "javascript",
            "typescript",
            "json",
            "jsonc",
            "lua",
            "luadoc",
            "luap",
            "markdown",
            "markdown_inline",
            "python",
            "php",
            "regex",
            "toml",
            "yaml",
            "vim",
            "vimdoc",
            "xml",
            "go",
            "gomod",
        }
    },
}
